### ISSUE TITLE
EPIC 1: Discovery

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#1]
This Epic is the first step in the process of making the website for the client. It contains the following tasks:

- [x] [Target Audience](https://github.com/Jereriviel/semester-project-1/issues/2)
- [x] [Competitors](https://github.com/Jereriviel/semester-project-1/issues/3)
- [ ] [Goals](https://github.com/Jereriviel/semester-project-1/issues/4)
- [x] [Brand Identity](https://github.com/Jereriviel/semester-project-1/issues/5)
