### ISSUE TITLE
EPIC 3: Planning

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#13]
This Epic is the third step in the process of making the website for the client. It contains the following tasks:

- [x] [Project setup](https://github.com/Jereriviel/semester-project-1/issues/63)
- [x] [GitHub setup](https://github.com/Jereriviel/semester-project-1/issues/62)
- [x] [Website map](https://github.com/Jereriviel/semester-project-1/issues/14)
- [x] [Content planning](https://github.com/Jereriviel/semester-project-1/issues/15)
- [x] [Content creation](https://github.com/Jereriviel/semester-project-1/issues/17)
- [x] [Wireframes](https://github.com/Jereriviel/semester-project-1/issues/16)
