### ISSUE TITLE
EPIC 5: HTML

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#25]
This Epic is the fifth step in the process of making the website for the client. It contains the following tasks:

Create the HTML for:

- [x] [Header and Navigation](https://github.com/Jereriviel/semester-project-1/issues/26)
- [x] [Footer](https://github.com/Jereriviel/semester-project-1/issues/26)
- [x] [Pages](https://github.com/Jereriviel/semester-project-1/issues/42)
- [x] Final review/refactoring.

**Comment by Jereriviel** [comment]
Final review and refactoring done.
