### ISSUE TITLE
EPIC 6: CSS

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#28]
This Epic is the sixth step in the process of making the website for the client. It contains the following tasks:

Create the CSS in the following CSS files:

- [x] [Styles](https://github.com/Jereriviel/semester-project-1/issues/29)
- [x] [Reset](https://github.com/Jereriviel/semester-project-1/issues/30)
- [x] [Variables](https://github.com/Jereriviel/semester-project-1/issues/31)
- [x] [Pages](https://github.com/Jereriviel/semester-project-1/issues/43)
- [x] Final review/refactoring.

**Comment by Jereriviel** [comment]
Final review and refactoring done.
