### ISSUE TITLE
EPIC 8: Launch

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#38]
Launch the website on GitHub.

- [x] [Deploy the website on GitHub.](https://github.com/Jereriviel/semester-project-1/issues/64)
- [x] Test the website in incognito mode.
- [x] Complete Testing Epic
- [x] Complete HTML Epic
- [x] Complete CSS Epic

**Comment by Jereriviel** [comment]
Website is launched.
