### ISSUE TITLE
EPIC 2: Strategy

### ISSUE THREAD

**Issue by Jereriviel** [Jereriviel/semester-project-1#6]
This Epic is the second step in the process of making the website for the client. It contains the following tasks:

- [x] [Project Scope](https://github.com/Jereriviel/semester-project-1/issues/7)
- [x] [Timeline](https://github.com/Jereriviel/semester-project-1/issues/8)
- [x] [Deliverables](https://github.com/Jereriviel/semester-project-1/issues/9)
- [x] [Site Architecture](https://github.com/Jereriviel/semester-project-1/issues/10)
- [x] [User stories](https://github.com/Jereriviel/semester-project-1/issues/12)
